### ISSUE TITLE
new error while starting image

### ISSUE THREAD

**Issue by Carunga** [sytone/obsidian-remote#14]
**Describe the bug**
The docker image does not start properly (anymore).In the logs I find the folliwing error:

obsidian-remote | [2022-07-11 10:57:25] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long                                                      obsidian-remote |     at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)                                                    obsidian-remote |     at listOnTimeout (internal/timers.js:557:17)                                                    obsidian-remote |     at processTimers (internal/timers.js:500:7)                                                     obsidian-remote | [2022-07-11 10:57:25] [Connection 1]  Closing guacd connection                                      obsidian-remote | [2022-07-11 10:57:25] [Connection 1]  Client connection closed                                      obsidian-remote | guacd[1424]: ERROR:   User is not responding.                                                       obsidian-remote | guacd[1424]: INFO:    User "@fe37cf9d-0ed2-4768-840b-9af059236e5b" disconnected (0 users remain)    obsidian-remote | guacd[1424]: INFO:    Last user of connection "$a3a619d9-3de7-449c-8e29-c6850a60b88f" disconnected  obsidian-remote | guacd[1424]: INFO:    Internal RDP client disconnected                                              obsidian-remote | guacd[1376]: INFO:    Connection "$a3a619d9-3de7-449c-8e29-c6850a60b88f" removed.                   obsidian-remote | rdpClientConRecv: g_sck_recv failed(returned 0)

Any ideas what went wrong?

**Comment by Carunga** [comment]
Ups, there was a browser related issue as well. The error persists, but Obsidian-Remote works now as expected. Sorry !
