### ISSUE TITLE
502 Bad-Gateway with docker compose and nginx

### ISSUE THREAD

**Issue by Pudding26** [sytone/obsidian-remote#52]
**Describe the bug**
I try to set up Obsidian with the docker compose file and NGINX, but when forwarding to my choosen port i get 502 error. I checked the logs of the container and they seem not healty to me but I am not certain. Maybe one you has an idea on what to try next.

**To Reproduce**
1.) Use docker compose from readme
2.) change ports to: my-port:8080
3.) add my NGINX network
4.) enable my-port in ufw

**Additional context**
Container Log:

`  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpResizeSession: width 1024 height 768
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 7
rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
rdpAddClientConToDev: adding first clientCon 0x55d757a55c60
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 1024 height 768 bpp 16
rdpClientConProcessScreenSizeMsg: shmemid 0 shmemptr 0x7f7b821d6000
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1024 cy 768
4.sync,10.3247251621;
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
(EE) Failed to open authorization file ".Xauthority": No such file or directory
rdpClientConProcessMsgClientInfo:
  got client info bytes 5752
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1024 height 768
rdpLoadLayout: keylayout 0x00000409 variant  display 10
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
4.sync,10.3247251796;
guacd[1130]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[1130]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[1130]: INFO:	Connected to RDPDR 1.12 as client 0x10afc144
3.end,1.1;5.audio,1.1,31.audio/L16;rate=22050,channels=2;4.sync,10.3247251797;
guacd[1130]: INFO:	RDPDR user logged on
4.sync,10.3247251799;
4.sync,10.3247251799;
3.img,1.3,2.14,1.0,9.image/png,1.0,1.0;4.blob,1.3,256.iVBORw0KGgoAAAANSUhEUgAABAAAAAMAAQMAAACAdIdOAAAAA1BMVEUAAACnej3aAAAAdklEQVR4nO3BAQEAAACCIP+vbkhAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7waDDwABtWbkhAAAAABJRU5ErkJggg==;3.end,1.3;4.sync,10.3247251862;
4.size,2.-1,2.32,2.32;3.img,1.3,2.12,2.-1,9.image/png,1.0,1.0;4.blob,1.3,256.iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAAdElEQVRYhe2VOxLAIAhEd5nc/8qkQcd8dNLIFuFVoAWPAUd4ABEGACShkrAWqCRsTBQSdj/IlngIZEu8CmRKTAWyJJYCGRLH7CJrDy8C7g6SPeeYbKKPIIqzdZ66hK347mKfic49Qu0rkKH+pouiKIqi+A8nWNBM/C9+/cYAAAAASUVORK5CYII=;3.end,1.3;6.cursor,1.1,1.1,2.-1,1.0,1.0,2.32,2.32;4.sync,10.3247251863;
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
4.sync,10.3247251901;
4.sync,10.3247252152;
4.sync,10.3247252402;
4.size,2.-1,2.32,2.32;3.img,1.3,2.12,2.-1,9.image/png,1.0,1.0;4.blob,1.3,256.iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAAdElEQVRYhe2VOxLAIAhEd5nc/8qkQcd8dNLIFuFVoAWPAUd4ABEGACShkrAWqCRsTBQSdj/IlngIZEu8CmRKTAWyJJYCGRLH7CJrDy8C7g6SPeeYbKKPIIqzdZ66hK347mKfic49Qu0rkKH+pouiKIqi+A8nWNBM/C9+/cYAAAAASUVORK5CYII=;3.end,1.3;6.cursor,1.1,1.1,2.-1,1.0,1.0,2.32,2.32;
4.sync,10.3247252482;
3.img,1.3,2.14,1.0,9.image/png,3.112,2.59;4.blob,1.3,212.iVBORw0KGgoAAAANSUhEUgAAAyAAAAKKAQMAAAD/Tq0XAAAAA1BMVEX///+nxBvIAAAAVklEQVR4nO3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOBhAIEAAYu38NAAAAAASUVORK5CYII=;3.end,1.3;4.sync,10.3247252533;
4.sync,10.3247252783;
4.sync,10.3247253034;
4.sync,10.3247253285;
4.sync,10.3247253537;
4.sync,10.3247253787;
4.sync,10.3247254038;
4.sync,10.3247254288;
4.sync,10.3247254539;
4.sync,10.3247254789;
4.sync,10.3247255039;
4.sync,10.3247255289;
4.sync,10.3247255540;
4.sync,10.3247255790;
4.sync,10.3247256040;
4.sync,10.3247256291;
4.sync,10.3247256541;
4.sync,10.3247256792;
4.sync,10.3247257042;
4.sync,10.3247257292;
4.sync,10.3247257542;
4.sync,10.3247257793;
4.sync,10.3247258043;
4.sync,10.3247258294;
4.sync,10.3247258544;
4.sync,10.3247258794;
4.sync,10.3247259045;
4.sync,10.3247259295;
4.sync,10.3247259545;
4.sync,10.3247259795;
[2023-05-07 01:24:10] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[2023-05-07 01:24:10] [Connection 1]  Closing guacd connection
[2023-05-07 01:24:10] [Connection 1]  Client connection closed
guacd[1130]: ERROR:	User is not responding.
guacd[1130]: INFO:	User "@c32db1b5-80df-455b-856f-c61fa54e39b3" disconnected (0 users remain)
guacd[1130]: INFO:	Last user of connection "$8b91fcbb-04bd-452a-8651-3ab21e4eeceb" disconnected
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0x55d757a55c60
guacd[1130]: INFO:	Internal RDP client disconnected
guacd[1097]: INFO:	Connection "$8b91fcbb-04bd-452a-8651-3ab21e4eeceb" removed.`

**Comment by dromalc** [comment]
I'm having the same issue.

**Comment by phil-gusev** [comment]
same

**Comment by huenfd** [comment]
same problem without nginx. I tried with custom user and password but no success. Has anybody found a solution?

**Comment by RedDTG** [comment]
Still the problem with nginx here, solution anyone ?
