### ISSUE TITLE
obsidian  | guacd[1106]: INFO:  Guacamole connection closed during handshake

### ISSUE THREAD

**Issue by stormyark** [sytone/obsidian-remote#98]
obsidian  | Starting guacamole-lite websocket server
obsidian  | events.js:377
obsidian  |       throw er; // Unhandled 'error' event
obsidian  |       ^
obsidian  |
obsidian  | Error: listen EACCES: permission denied "8080"
obsidian  |     at Server.setupListenHandle [as _listen2] (net.js:1314:21)
obsidian  |     at listenInCluster (net.js:1379:12)
obsidian  |     at Server.listen (net.js:1476:5)
obsidian  |     at Object.<anonymous> (/gclient/app.js:217:6)
obsidian  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
obsidian  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
obsidian  |     at Module.load (internal/modules/cjs/loader.js:950:32)
obsidian  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
obsidian  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
obsidian  |     at internal/main/run_main_module.js:17:47
obsidian  | Emitted 'error' event on WebSocketServer instance at:
obsidian  |     at Server.WebSocketServer._onServerError (/gclient/node_modules/ws/lib/WebSocketServer.js:82:50)
obsidian  |     at Server.emit (events.js:400:28)
obsidian  |     at emitErrorNT (net.js:1358:8)
obsidian  |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
obsidian  |   code: 'EACCES',
obsidian  |   errno: -13,
obsidian  |   syscall: 'listen',
obsidian  |   address: '"8080"',
obsidian  |   port: -1
obsidian  | }
obsidian  | guacd[1106]: INFO:  Guacamole connection closed during handshake

**Comment by ghostersk** [comment]
I think the issue is when you use the env variable for HTTP port.

**Comment by Dane-Fisher** [comment]
> I think the issue is when you use the env variable for HTTP port.

This is exactly the issue. Remove  CUSTOM_PORT="8080" as an env variable and it should be good to go.
