### ISSUE TITLE
remote guacamole connection error

### ISSUE THREAD

**Issue by matt22free** [sytone/obsidian-remote#99]
Installing Obsidian-remote on Synology docker (directly or with portainer)
Still have the same issue each time i try to start it : 
[2024-07-14 13:52:34] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[2024-07-14 13:52:34] [Connection 1]  Closing guacd connection
[2024-07-14 13:52:34] [Connection 1]  Client connection closed

here the full log : 

rdpmousePlug:

rdpkeybPlug:

rdpIdentify:
rdpDriverFunc: op 10

:
rdpProbe: found DRMDevice xorg.conf value [/dev/dri/renderD128]
rdpProbe: found DRI3 xorg.conf value [1]
rdpPreInit:
rdpPreInit: /dev/dri/renderD128 open failed
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x7f0ed48b6010
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x000706a8 bx 0x04400800 cx 0x4ff8ebbf dx 0xbfebfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpClientConInit: disconnect idle session after [0] sec
rdpClientConInit: kill disconnected [0] timeout [0] sec
rdpXvInit: depth 24
rdpScreenInit: out
4.sync,8.26542832;
[2024-07-14 13:52:34] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[2024-07-14 13:52:34] [Connection 1]  Closing guacd connection
[2024-07-14 13:52:34] [Connection 1]  Client connection closed
rdpCreateScreenResources:
rdpmousePreInit: drv 0x55cc46b52010 info 0x55cc46cb7f90, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0x7f0ed5e1c430
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0x55cc46b41460 info 0x55cc46e3fe90, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0x7f0ed4fa78e0
rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpResizeSession: width 1024 height 768
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 7
rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
rdpAddClientConToDev: adding first clientCon 0x55cc46eb8750
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 1024 height 768 bpp 16
rdpClientConProcessScreenSizeMsg: shmemid 0 shmemptr 0x7f0ed490b000
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1024 cy 768
(EE) Failed to open authorization file ".Xauthority": No such file or directory
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpRRGetInfo:
rdpClientConProcessMsgClientInfo:
  got client info bytes 5752
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1024 height 768
rdpLoadLayout: keylayout 0x00000409 variant  display 10
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
guacd[1190]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[1190]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[1190]: INFO:	Connected to RDPDR 1.12 as client 0x7afd159b
guacd[1190]: INFO:	RDPDR user logged on
guacd[1190]: ERROR:	User is not responding.
guacd[1190]: INFO:	User "@33076660-9740-4275-b3cd-5920cdae815c" disconnected (0 users remain)
guacd[1190]: INFO:	Last user of connection "$2fc13fe0-a088-4dac-b8f2-3eb8a7ec5dbc" disconnected
guacd[1190]: INFO:	Internal RDP client disconnected
guacd[1128]: INFO:	Connection "$2fc13fe0-a088-4dac-b8f2-3eb8a7ec5dbc" removed.
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0x55cc46eb8750

**Comment by christophervelo** [comment]
I ran into the same issue. I cant quite figure it out but will be testing this again once its resolved

**Comment by jessemcdowell** [comment]
I'm also getting this. I am attempting to run the container in podman on Debian:

```bash
podman pod create --name obsidian \
	-v /storage/obsidian/config:/config \
	-v /storage/obsidian/vaults:/vaults \
	--publish 8080:8080

podman create --pod obsidian --name obsidian-app \
	--pull newer --restart on-failure:10 \
	-e TZ=America/Vancouver \
	ghcr.io/sytone/obsidian-remote:latest

podman pod start obsidian
```

And the logs end with this:
```
[2025-01-30 11:30:49] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[2025-01-30 11:30:49] [Connection 1]  Closing guacd connection
[2025-01-30 11:30:49] [Connection 1]  Client connection closed
guacd[225]: ERROR:      User is not responding.
guacd[225]: INFO:       User "@04226e34-64e2-4946-a425-841c9e166a44" disconnected (0 users remain)
guacd[225]: INFO:       Last user of connection "$9d1c8f85-774b-4a87-b0c0-ab62de9597d4" disconnected
guacd[225]: INFO:       Internal RDP client disconnected
guacd[188]: INFO:       Connection "$9d1c8f85-774b-4a87-b0c0-ab62de9597d4" removed.
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0x55b328153c60
```

**Comment by jessemcdowell** [comment]
I also tried building a new image from the repo. I am able to access the web-based VNC, but Obsidian fails to start with a different error.

**Comment by seemslikeali** [comment]
I'm having the same issue...

**Comment by chaonetic** [comment]
Have you solved this problem?

**Comment by chaonetic** [comment]
> 我遇到了同样的问题...

I also have this problem, please solve it @seemslikeali

**Comment by seemslikeali** [comment]
Ask the developers. I found something else.
